services:
  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "9001:5432"
    environment:
      POSTGRES_USER: listdbuser
      POSTGRES_PASSWORD: listdbpass
      POSTGRES_DB: listdb
  web:
    build: .
    restart: always
    ports:
      - "9000:9000"
